### ISSUE TITLE
Error compiling with GnatStudio

### ISSUE THREAD

**Issue by sanyaade-teachings** [godunko/hexapod#1]
Hi All,

I wanted to use this package to port my Vex Robotics Cortex-M3 controller but I am having a build issue with it as shown below

![image](https://github.com/godunko/hexapod/assets/4993211/e76a9018-b733-4710-a8a1-6b109c17adc3)

the issues are with the [ ]  in Step  => [(L_1 => 0, L_2 => 0, L_3 => 0, L_4 => 0, L_5 => 0, L_6 => 0)] being seen as illegal characters

Please help

God blesses!!!

Regards

**Comment by godunko** [comment]
Hello,

'[' is new syntax for array initialization in Ada 2022. You need to have recent enough compiler (I've developed code with FSF GCC 13.2 from Alire) and define `-gnat2022` compiler switch or add `pragma Ada_2022;` line at the beginning of the file.

Also, `phoenyx.gpr` is not intended to be used to build projects, it allows to open all sources of the project and edit/navigate in the source code. You need to use individual project files from `gnat` subdirectory to build particular component (binary file for Arduino Due is build by `gnat/arduino.gpr`, native examples and tests by `gnat/examples.gpr`).

**Comment by sanyaade-teachings** [comment]
> Hello,
> 
> '[' is new syntax for array initialization in Ada 2022. You need to have recent enough compiler (I've developed code with FSF GCC 13.2 from Alire) and define `-gnat2022` compiler switch or add `pragma Ada_2022;` line at the beginning of the file.
> 
> Also, `phoenyx.gpr` is not intended to be used to build projects, it allows to open all sources of the project and edit/navigate in the source code. You need to use individual project files from `gnat` subdirectory to build particular component (binary file for Arduino Due is build by `gnat/arduino.gpr`, native examples and tests by `gnat/examples.gpr`).

Hi, 

Many thanks for the feedback and pointers.
I will follow your direction to things done.

Once again, many thanks!

God blesses!!!

Regards
